[package]
name = "oakterm-daemon"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "OakTerm daemon process"

[dependencies]
bytes = { workspace = true }
oakterm-config = { path = "../oakterm-config" }
oakterm-mux = { path = "../oakterm-mux" }
oakterm-protocol = { path = "../oakterm-protocol" }
oakterm-pty = { path = "../oakterm-pty" }
oakterm-terminal = { path = "../oakterm-terminal" }
rustix = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
shlex = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
oakterm-terminal = { path = "../oakterm-terminal", features = ["test-hooks"] }
tempfile = "3.27.0"

[build-dependencies]
vergen = { workspace = true }
vergen-gitcl = { workspace = true }

[lints]
workspace = true
